name: Update GFWList

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 支持手动触发
  push:
    paths:
      - '.github/workflows/update-gfwlist.yml'
      - '.github/scripts/gfwlist_converter.py'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0   # 获取完整的 git 历史
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Update GFWList
      run: python .github/scripts/gfwlist_converter.py
        
    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code list/gfwlist.conf || echo "changes=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull --rebase origin main  # 先拉取并变基
        git add list/gfwlist.conf
        git commit -m "chore: update gfwlist.conf [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}