name: Sync Files

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Add manual trigger inputs if needed
    inputs:
      dry_run:
        description: 'Perform a dry run without pushing changes'
        type: boolean
        default: false

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add timeout to prevent hanging jobs
    
    # Prevent concurrent runs of the same workflow
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
        
      - name: Sync Files
        id: sync
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python .github/scripts/sync_files.py
        continue-on-error: false

      - name: Commit changes
        if: success() && !inputs.dry_run
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check for changes
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Stage and commit changes
          git add .
          git commit -m "chore: sync files from remote source [skip ci]
          
          Automated sync performed by GitHub Actions"
          git push
          
      - name: Error notification
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Sync Files workflow failed',
              body: `Workflow run failed: ${process.env.GITHUB_SERVER_URL}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })