name: Sync Files

on:
  schedule:
    # 每天凌晨2点运行
    - cron: '0 2 * * *'
  # 也可以手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}  # 使用 PAT 进行checkout

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sync Files
        run: |
          python .github/scripts/sync_files.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Sync: Update files from remote source" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # 使用 PAT 进行push